# theme: jekyll-theme-cayman
title: JAGSMAP
description: Jaguars At the Global Scale -- a Meta-Analysis of the Population
highlighter: rouge

# By default, the navbar creates a link for every "page" containing a `title`
# attribute, so long as the title does not include "404". Override the
# default links by defining a `site.header_paths` array:
header_paths:
- about.md
- experience.md
- projects.md
# - research.md

##### BUILD SETTINGS #####
# incremental: true

# strip all unncessary whitespace and comments
# http://jch.penibelst.de/
compress_html:
  blanklines: true
